var my_array = ["amit", "sumit","randiwatam"];

// // using the push()
// my_array.push("amol","mahibhai");
// console.log(my_array);

// // using the pop()
// var removedarray = my_array.pop();
// console.log(removedarray)
// console.log(my_array)

// using the shift
// my_array.shift("amol")
// var removedarray = console.log(my_array);

// using the unshift
my_array.unshift("randiwatam")
var remvedarray = console.log(my_array);